"""initial schema

Revision ID: c1d1b5fb56d4
Revises: 
Create Date: 2026-04-06 03:15:28.934635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1d1b5fb56d4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stream_id', sa.String(length=128), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('mentions_bot', sa.Boolean(), nullable=False),
    sa.Column('message_id', sa.String(length=255), nullable=True),
    sa.Column('reply_to_message_id', sa.String(length=255), nullable=True),
    sa.Column('reply_to_username', sa.String(length=64), nullable=True),
    sa.Column('reply_to_text', sa.Text(), nullable=True),
    sa.Column('is_memory_processed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_created_at'), 'chat_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_is_memory_processed'), 'chat_messages', ['is_memory_processed'], unique=False)
    op.create_index(op.f('ix_chat_messages_mentions_bot'), 'chat_messages', ['mentions_bot'], unique=False)
    op.create_index(op.f('ix_chat_messages_message_id'), 'chat_messages', ['message_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_reply_to_message_id'), 'chat_messages', ['reply_to_message_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_role'), 'chat_messages', ['role'], unique=False)
    op.create_index(op.f('ix_chat_messages_stream_id'), 'chat_messages', ['stream_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_username'), 'chat_messages', ['username'], unique=False)
    op.create_table('knowledge_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tags', sa.String(length=512), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_items_source_name'), 'knowledge_items', ['source_name'], unique=False)
    op.create_index(op.f('ix_knowledge_items_title'), 'knowledge_items', ['title'], unique=False)
    op.create_index(op.f('ix_knowledge_items_updated_at'), 'knowledge_items', ['updated_at'], unique=False)
    op.create_table('stream_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stream_id', sa.String(length=128), nullable=False),
    sa.Column('window_label', sa.String(length=64), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stream_summaries_created_at'), 'stream_summaries', ['created_at'], unique=False)
    op.create_index(op.f('ix_stream_summaries_stream_id'), 'stream_summaries', ['stream_id'], unique=False)
    op.create_index(op.f('ix_stream_summaries_window_label'), 'stream_summaries', ['window_label'], unique=False)
    op.create_table('user_memory_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_memory_items_created_at'), 'user_memory_items', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_memory_items_kind'), 'user_memory_items', ['kind'], unique=False)
    op.create_index(op.f('ix_user_memory_items_updated_at'), 'user_memory_items', ['updated_at'], unique=False)
    op.create_index(op.f('ix_user_memory_items_username'), 'user_memory_items', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_memory_items_username'), table_name='user_memory_items')
    op.drop_index(op.f('ix_user_memory_items_updated_at'), table_name='user_memory_items')
    op.drop_index(op.f('ix_user_memory_items_kind'), table_name='user_memory_items')
    op.drop_index(op.f('ix_user_memory_items_created_at'), table_name='user_memory_items')
    op.drop_table('user_memory_items')
    op.drop_index(op.f('ix_stream_summaries_window_label'), table_name='stream_summaries')
    op.drop_index(op.f('ix_stream_summaries_stream_id'), table_name='stream_summaries')
    op.drop_index(op.f('ix_stream_summaries_created_at'), table_name='stream_summaries')
    op.drop_table('stream_summaries')
    op.drop_index(op.f('ix_knowledge_items_updated_at'), table_name='knowledge_items')
    op.drop_index(op.f('ix_knowledge_items_title'), table_name='knowledge_items')
    op.drop_index(op.f('ix_knowledge_items_source_name'), table_name='knowledge_items')
    op.drop_table('knowledge_items')
    op.drop_index(op.f('ix_chat_messages_username'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_stream_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_role'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_reply_to_message_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_message_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_mentions_bot'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_is_memory_processed'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_created_at'), table_name='chat_messages')
    op.drop_table('chat_messages')
    # ### end Alembic commands ###
