"""add memory pipeline fields

Revision ID: f7ca29f2917a
Revises: 528ab8411a47
Create Date: 2026-04-06 01:25:59.824318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7ca29f2917a'
down_revision: Union[str, Sequence[str], None] = '528ab8411a47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('message_id', sa.String(length=255), nullable=True))
    op.add_column('chat_messages', sa.Column('reply_to_message_id', sa.String(length=255), nullable=True))
    op.add_column('chat_messages', sa.Column('reply_to_username', sa.String(length=64), nullable=True))
    op.add_column('chat_messages', sa.Column('reply_to_text', sa.Text(), nullable=True))
    op.create_index(op.f('ix_chat_messages_message_id'), 'chat_messages', ['message_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_reply_to_message_id'), 'chat_messages', ['reply_to_message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_messages_reply_to_message_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_message_id'), table_name='chat_messages')
    op.drop_column('chat_messages', 'reply_to_text')
    op.drop_column('chat_messages', 'reply_to_username')
    op.drop_column('chat_messages', 'reply_to_message_id')
    op.drop_column('chat_messages', 'message_id')
    # ### end Alembic commands ###
